### PR TITLE
Adding Operator command identify

### PR DESCRIPTION
**Pull request by tinaira**
Now you will be able to identify you'r self as a operator now on.

### CODE REVIEW

**Comment by jhthorsen** [comment]
I don't think this will work, since the "OPER" command is not supported in the backend.

**Comment by jhthorsen** [comment]
https://github.com/Nordaaker/convos/blob/master/lib/Convos/Core/Connection/Irc.pm#L164

**Comment by tinaira** [comment]
@jhthorsen ou damn :a:

**Comment by jhthorsen** [comment]
Unfortunately, it's not that simple. I will look at this evening.

**Comment by tinaira** [comment]
Thank you

**Comment by jhthorsen** [comment]
@tinaira: Could you check if the OPER command is supported now? There's no autocomplete, but it should be supported in version 0.99_24 (62ec62285927787b263396a12b99e76fb001cbdc)

**Comment by jhthorsen** [comment]
I'm closing this because it has been inactive for quite some time.

**Pull request closed without merging**
